# database generated on 2023-12-05 08:11 GMT
!!omap
- /home/quswarabid/ara/apps/riscof/test_suite/vadd.S:
    commit_id: '-'
    isa:
    - RV64RV64IMAFDCVZicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*V.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - vadd
