

.PHONY : TARGET0
TARGET0 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vadc.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vadc.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET1
TARGET1 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vadd.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vadd.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET2
TARGET2 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vand.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vand.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET3
TARGET3 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vdiv.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vdiv.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET4
TARGET4 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vdivu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vdivu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET5
TARGET5 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmacc.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmacc.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET6
TARGET6 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmadc.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmadc.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET7
TARGET7 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmadd.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmadd.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET8
TARGET8 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmax.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmax.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET9
TARGET9 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmaxu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmaxu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET10
TARGET10 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmin.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmin.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET11
TARGET11 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vminu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vminu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET12
TARGET12 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmsbc.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmsbc.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET13
TARGET13 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmseq.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmseq.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET14
TARGET14 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmsgt.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmsgt.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET15
TARGET15 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmsgtu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmsgtu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET16
TARGET16 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmsle.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmsle.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET17
TARGET17 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmsleu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmsleu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET18
TARGET18 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmslt.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmslt.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET19
TARGET19 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmsltu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmsltu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET20
TARGET20 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmsne.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmsne.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET21
TARGET21 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmul.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmul.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET22
TARGET22 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmulh.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmulh.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET23
TARGET23 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmulhsu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmulhsu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET24
TARGET24 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vmulhu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vmulhu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET25
TARGET25 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vor.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vor.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET26
TARGET26 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vredand.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vredand.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET27
TARGET27 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vredmax.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vredmax.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET28
TARGET28 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vredmaxu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vredmaxu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET29
TARGET29 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vredmin.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vredmin.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET30
TARGET30 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vredminu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vredminu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET31
TARGET31 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vredor.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vredor.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET32
TARGET32 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vredsum.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vredsum.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET33
TARGET33 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vredxor.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vredxor.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET34
TARGET34 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vrem.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vrem.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET35
TARGET35 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vremu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vremu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET36
TARGET36 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vrsub.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vrsub.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET37
TARGET37 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vsadd.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vsadd.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET38
TARGET38 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vsaddu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vsaddu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET39
TARGET39 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vsbc.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vsbc.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET40
TARGET40 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vsext.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vsext.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET41
TARGET41 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vsll.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vsll.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET42
TARGET42 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vsra.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vsra.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET43
TARGET43 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vsrl.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vsrl.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET44
TARGET44 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vssub.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vssub.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET45
TARGET45 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vssubu.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vssubu.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET46
TARGET46 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vsub.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vsub.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET47
TARGET47 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vxor.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vxor.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;

.PHONY : TARGET48
TARGET48 :
	@cd /home/quswarabid/ara/apps/riscof/riscof_work/vzext.S/dut; /home/quswarabid/ara/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -march=rv64gv          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/quswarabid/ara/apps/riscof/ara/env/link.ld         -I /home/quswarabid/ara/apps/riscof/ara/env/         -I /home/quswarabid/ara/apps/riscof/env /home/quswarabid/ara/apps/riscof/test_suite/vzext.S /home/quswarabid/ara/apps/common/crt0.S  -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -DFLEN=64 -mabi=lp64; /home/quswarabid/ara/hardware/build/verilator/Vara_tb_verilator -l ram,my.elf,elf 1>stdout 2>stderr;